name: Build Docker Image
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  # Change variable to your image's name.
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_BRANCH: ${{ github.ref }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo $IMAGE_NAME:IMAGE_BRANCH
        
        docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_BRANCH
